---
# Install https://github.com/lovoo/jenkins_exporter

- name: Install python requirements
  pip:
    name: "{{ item }}"
  with_items:
    - prometheus-client==0.1.0
    - requests==2.10.0
- name: Download Jenkins exporter
  get_url:
    url: https://raw.githubusercontent.com/lovoo/jenkins_exporter/master/jenkins_exporter.py
    dest: /usr/bin/jenkins_exporter.py
    mode: '0444'
  notify: restart jenkins_exporter
- name: Create Jenkins exporter service definition
  template:
    src: jenkins_exporter.service.j2
    dest: /lib/systemd/system/jenkins_exporter.service
  notify: restart jenkins_exporter
- name: Start Jenkins Exporter service
  service:
    name: jenkins_exporter
    enabled: yes
    state: started
  become: true
